#!/bin/sh

# required for octorprint
ln -s /lib/libc.so.0 /lib/libc.so.6

# add enviroment var for python
echo export PYTHONPATH=/mnt/octoprint-packages >> /etc/profile
echo export PATH=${PATH}:/mnt/usrbin >> /etc/profile

return 0
