#!/bin/sh

# create a octoprint file in init
# octoprint will auto start after following command
# /etc/init.d/octoprint enable
cat > /etc/init.d/octoprint << EOF
#!/bin/sh /etc/rc.common

START=99

start() {
	echo start octoprint
	. /etc/profile
	start_octoprint
}
EOF

chmod 755 /etc/init.d/octoprint

/etc/init.d/octoprint enable

# required for octorprint
ln -s /lib/libc.so.0 /lib/libc.so.6

# add enviroment var for python
echo export PYTHONPATH=/mnt/octoprint-packages >> /etc/profile
echo export PATH=${PATH}:/mnt/usrbin >> /etc/profile

return 0
