#!/bin/sh

# create a octoprint file
cat > /usr/bin/octoprint << EOF
#!/usr/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'OctoPrint==1.2.6','console_scripts','octoprint'
__requires__ = 'OctoPrint==1.2.6'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
    load_entry_point('OctoPrint==1.2.6', 'console_scripts', 'octoprint')()
    )
EOF

chmod 755 /usr/bin/octoprint

ln -s /lib/libc.so.0 /lib/libc.so.6

# link all py packages from sd card

ln -s /mnt/usr/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg /usr/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg /usr/lib/python2.7/site-packages/argh-0.26.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/babel /usr/lib/python2.7/site-packages/babel
ln -s /mnt/usr/lib/python2.7/site-packages/babel /usr/lib/python2.7/site-packages/babel
ln -s /mnt/usr/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg-info /usr/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg-info /usr/lib/python2.7/site-packages/Babel-0.9.6-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Babel-2.1.1-py2.7.egg /usr/lib/python2.7/site-packages/Babel-2.1.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/Babel-2.1.1-py2.7.egg /usr/lib/python2.7/site-packages/Babel-2.1.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/blinker-1.4-py2.7.egg /usr/lib/python2.7/site-packages/blinker-1.4-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/blinker-1.4-py2.7.egg /usr/lib/python2.7/site-packages/blinker-1.4-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/curl /usr/lib/python2.7/site-packages/curl
ln -s /mnt/usr/lib/python2.7/site-packages/curl /usr/lib/python2.7/site-packages/curl
ln -s /mnt/usr/lib/python2.7/site-packages/dns /usr/lib/python2.7/site-packages/dns
ln -s /mnt/usr/lib/python2.7/site-packages/dns /usr/lib/python2.7/site-packages/dns
ln -s /mnt/usr/lib/python2.7/site-packages/dnspython-1.12.0-py2.7.egg-info /usr/lib/python2.7/site-packages/dnspython-1.12.0-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/dnspython-1.12.0-py2.7.egg-info /usr/lib/python2.7/site-packages/dnspython-1.12.0-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/easy_install.pth /usr/lib/python2.7/site-packages/easy_install.pth
ln -s /mnt/usr/lib/python2.7/site-packages/easy_install.pth /usr/lib/python2.7/site-packages/easy_install.pth
ln -s /mnt/usr/lib/python2.7/site-packages/easy-install.pth /usr/lib/python2.7/site-packages/easy-install.pth
ln -s /mnt/usr/lib/python2.7/site-packages/easy-install.pth /usr/lib/python2.7/site-packages/easy-install.pth
ln -s /mnt/usr/lib/python2.7/site-packages/flask /usr/lib/python2.7/site-packages/flask
ln -s /mnt/usr/lib/python2.7/site-packages/flask /usr/lib/python2.7/site-packages/flask
ln -s /mnt/usr/lib/python2.7/site-packages/flask-0.10.1-py2.7.egg /usr/lib/python2.7/site-packages/flask-0.10.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask-0.10.1-py2.7.egg /usr/lib/python2.7/site-packages/flask-0.10.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask-0.11.dev0-py2.7.egg /usr/lib/python2.7/site-packages/Flask-0.11.dev0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/Flask-0.11.dev0-py2.7.egg /usr/lib/python2.7/site-packages/Flask-0.11.dev0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_assets-0.10-py2.7.egg /usr/lib/python2.7/site-packages/flask_assets-0.10-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_assets-0.10-py2.7.egg /usr/lib/python2.7/site-packages/flask_assets-0.10-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_babel-0.9-py2.7.egg /usr/lib/python2.7/site-packages/flask_babel-0.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_babel-0.9-py2.7.egg /usr/lib/python2.7/site-packages/flask_babel-0.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Bcrypt-0.7.1-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Bcrypt-0.7.1-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Bcrypt-0.7.1-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Bcrypt-0.7.1-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Classy-0.6.10-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Classy-0.6.10-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Classy-0.6.10-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Classy-0.6.10-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/flaskext /usr/lib/python2.7/site-packages/flaskext
ln -s /mnt/usr/lib/python2.7/site-packages/flaskext /usr/lib/python2.7/site-packages/flaskext
ln -s /mnt/usr/lib/python2.7/site-packages/flask_login-0.2.2-py2.7.egg /usr/lib/python2.7/site-packages/flask_login-0.2.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_login-0.2.2-py2.7.egg /usr/lib/python2.7/site-packages/flask_login-0.2.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Markdown-0.3-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Markdown-0.3-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Flask_Markdown-0.3-py2.7.egg-info /usr/lib/python2.7/site-packages/Flask_Markdown-0.3-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/flask_principal-0.3.5-py2.7.egg /usr/lib/python2.7/site-packages/flask_principal-0.3.5-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_principal-0.3.5-py2.7.egg /usr/lib/python2.7/site-packages/flask_principal-0.3.5-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_principal-0.4.0-py2.7.egg /usr/lib/python2.7/site-packages/flask_principal-0.4.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/flask_principal-0.4.0-py2.7.egg /usr/lib/python2.7/site-packages/flask_principal-0.4.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous-0.22-py2.7.egg-info /usr/lib/python2.7/site-packages/itsdangerous-0.22-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous-0.22-py2.7.egg-info /usr/lib/python2.7/site-packages/itsdangerous-0.22-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous.py /usr/lib/python2.7/site-packages/itsdangerous.py
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous.py /usr/lib/python2.7/site-packages/itsdangerous.py
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous.pyc /usr/lib/python2.7/site-packages/itsdangerous.pyc
ln -s /mnt/usr/lib/python2.7/site-packages/itsdangerous.pyc /usr/lib/python2.7/site-packages/itsdangerous.pyc
ln -s /mnt/usr/lib/python2.7/site-packages/jinja2 /usr/lib/python2.7/site-packages/jinja2
ln -s /mnt/usr/lib/python2.7/site-packages/jinja2 /usr/lib/python2.7/site-packages/jinja2
ln -s /mnt/usr/lib/python2.7/site-packages/Jinja2-2.7-py2.7.egg-info /usr/lib/python2.7/site-packages/Jinja2-2.7-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/Jinja2-2.7-py2.7.egg-info /usr/lib/python2.7/site-packages/Jinja2-2.7-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/markupsafe /usr/lib/python2.7/site-packages/markupsafe
ln -s /mnt/usr/lib/python2.7/site-packages/markupsafe /usr/lib/python2.7/site-packages/markupsafe
ln -s /mnt/usr/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7.egg-info /usr/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7.egg-info /usr/lib/python2.7/site-packages/MarkupSafe-0.18-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/MySQLdb /usr/lib/python2.7/site-packages/MySQLdb
ln -s /mnt/usr/lib/python2.7/site-packages/MySQLdb /usr/lib/python2.7/site-packages/MySQLdb
ln -s /mnt/usr/lib/python2.7/site-packages/_mysql_exceptions.py /usr/lib/python2.7/site-packages/_mysql_exceptions.py
ln -s /mnt/usr/lib/python2.7/site-packages/_mysql_exceptions.py /usr/lib/python2.7/site-packages/_mysql_exceptions.py
ln -s /mnt/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7.egg-info /usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7.egg-info /usr/lib/python2.7/site-packages/MySQL_python-1.2.5-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/_mysql.so /usr/lib/python2.7/site-packages/_mysql.so
ln -s /mnt/usr/lib/python2.7/site-packages/_mysql.so /usr/lib/python2.7/site-packages/_mysql.so
ln -s /mnt/usr/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg /usr/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg /usr/lib/python2.7/site-packages/netaddr-0.7.17-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/netaddr-0.7.18-py2.7.egg-info /usr/lib/python2.7/site-packages/netaddr-0.7.18-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/netaddr-0.7.18-py2.7.egg-info /usr/lib/python2.7/site-packages/netaddr-0.7.18-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/OctoPrint-1.2.6-py2.7.egg /usr/lib/python2.7/site-packages/OctoPrint-1.2.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/OctoPrint-1.2.6-py2.7.egg /usr/lib/python2.7/site-packages/OctoPrint-1.2.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg /usr/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg /usr/lib/python2.7/site-packages/pathtools-0.1.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/PIL /usr/lib/python2.7/site-packages/PIL
ln -s /mnt/usr/lib/python2.7/site-packages/PIL /usr/lib/python2.7/site-packages/PIL
ln -s /mnt/usr/lib/python2.7/site-packages/PIL.pth /usr/lib/python2.7/site-packages/PIL.pth
ln -s /mnt/usr/lib/python2.7/site-packages/PIL.pth /usr/lib/python2.7/site-packages/PIL.pth
ln -s /mnt/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg /usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg /usr/lib/python2.7/site-packages/pip-1.5.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg /usr/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg /usr/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pkg_resources /usr/lib/python2.7/site-packages/pkg_resources
ln -s /mnt/usr/lib/python2.7/site-packages/pkg_resources /usr/lib/python2.7/site-packages/pkg_resources
ln -s /mnt/usr/lib/python2.7/site-packages/-3.1.1-py2.7-win32.egg /usr/lib/python2.7/site-packages/-3.1.1-py2.7-win32.egg
ln -s /mnt/usr/lib/python2.7/site-packages/-3.1.1-py2.7-win32.egg /usr/lib/python2.7/site-packages/-3.1.1-py2.7-win32.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg /usr/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg /usr/lib/python2.7/site-packages/pyasn1-0.1.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pycurl-7.19.0-py2.7.egg-info /usr/lib/python2.7/site-packages/pycurl-7.19.0-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/pycurl-7.19.0-py2.7.egg-info /usr/lib/python2.7/site-packages/pycurl-7.19.0-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/pycurl.so /usr/lib/python2.7/site-packages/pycurl.so
ln -s /mnt/usr/lib/python2.7/site-packages/pycurl.so /usr/lib/python2.7/site-packages/pycurl.so
ln -s /mnt/usr/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg /usr/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg /usr/lib/python2.7/site-packages/pylru-1.0.9-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg-info /usr/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg-info /usr/lib/python2.7/site-packages/pyserial-2.7-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/pytz-2015.6-py2.7.egg /usr/lib/python2.7/site-packages/pytz-2015.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/pytz-2015.6-py2.7.egg /usr/lib/python2.7/site-packages/pytz-2015.6-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/PyYAML-3.08-py2.7.egg-info /usr/lib/python2.7/site-packages/PyYAML-3.08-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/PyYAML-3.08-py2.7.egg-info /usr/lib/python2.7/site-packages/PyYAML-3.08-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7.egg-info /usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7.egg-info /usr/lib/python2.7/site-packages/PyYAML-3.11-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/README /usr/lib/python2.7/site-packages/README
ln -s /mnt/usr/lib/python2.7/site-packages/README /usr/lib/python2.7/site-packages/README
ln -s /mnt/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg /usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg /usr/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/rsa-3.2-py2.7.egg /usr/lib/python2.7/site-packages/rsa-3.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/rsa-3.2-py2.7.egg /usr/lib/python2.7/site-packages/rsa-3.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg /usr/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg /usr/lib/python2.7/site-packages/sarge-0.1.4-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg /usr/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg /usr/lib/python2.7/site-packages/semantic_version-2.4.2-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/serial /usr/lib/python2.7/site-packages/serial
ln -s /mnt/usr/lib/python2.7/site-packages/serial /usr/lib/python2.7/site-packages/serial
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools /usr/lib/python2.7/site-packages/setuptools
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools /usr/lib/python2.7/site-packages/setuptools
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools-16.0.dist-info /usr/lib/python2.7/site-packages/setuptools-16.0.dist-info
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools-16.0.dist-info /usr/lib/python2.7/site-packages/setuptools-16.0.dist-info
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg /usr/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg /usr/lib/python2.7/site-packages/setuptools-7.0-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools.pth /usr/lib/python2.7/site-packages/setuptools.pth
ln -s /mnt/usr/lib/python2.7/site-packages/setuptools.pth /usr/lib/python2.7/site-packages/setuptools.pth
ln -s /mnt/usr/lib/python2.7/site-packages/site.py /usr/lib/python2.7/site-packages/site.py
ln -s /mnt/usr/lib/python2.7/site-packages/site.py /usr/lib/python2.7/site-packages/site.py
ln -s /mnt/usr/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg /usr/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg /usr/lib/python2.7/site-packages/sockjs_tornado-1.0.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg /usr/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg /usr/lib/python2.7/site-packages/speaklater-1.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/tornado /usr/lib/python2.7/site-packages/tornado
ln -s /mnt/usr/lib/python2.7/site-packages/tornado /usr/lib/python2.7/site-packages/tornado
ln -s /mnt/usr/lib/python2.7/site-packages/tornado-4.0.2-py2.7.egg-info /usr/lib/python2.7/site-packages/tornado-4.0.2-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/tornado-4.0.2-py2.7.egg-info /usr/lib/python2.7/site-packages/tornado-4.0.2-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/tornado-4.3-py2.7.egg-info /usr/lib/python2.7/site-packages/tornado-4.3-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/tornado-4.3-py2.7.egg-info /usr/lib/python2.7/site-packages/tornado-4.3-py2.7.egg-info
ln -s /mnt/usr/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg /usr/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg /usr/lib/python2.7/site-packages/watchdog-0.8.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg /usr/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg /usr/lib/python2.7/site-packages/webassets-0.11.1-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/werkzeug-0.8.3-py2.7.egg /usr/lib/python2.7/site-packages/werkzeug-0.8.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/werkzeug-0.8.3-py2.7.egg /usr/lib/python2.7/site-packages/werkzeug-0.8.3-py2.7.egg
ln -s /mnt/usr/lib/python2.7/site-packages/yaml /usr/lib/python2.7/site-packages/yaml
ln -s /mnt/usr/lib/python2.7/site-packages/yaml /usr/lib/python2.7/site-packages/yaml
ln -s /mnt/usr/lib/python2.7/site-packages/_yaml.so /usr/lib/python2.7/site-packages/_yaml.so
ln -s /mnt/usr/lib/python2.7/site-packages/_yaml.so /usr/lib/python2.7/site-packages/_yaml.so


return 0


