#!/bin/sh

. /lib/functions.sh

uci delete fstab.@mount[0]
uci add fstab mount
uci set fstab.@mount[0].target='/mnt'
uci set fstab.@mount[0].options='sync'
uci set fstab.@mount[0].device='/dev/mmcblk0p1'

uci commit

exit 0
