#!/bin/sh

. /lib/functions.sh

uci set fstab.@mount[0].target='/mnt'
uci set fstab.@mount[0].options='sync'
uci set fstab.@mount[0].device='/dev/mmcblk0p1'
uci delete fstab.@mount[0].uuid
uci delete fstab.@mount[0].enabled

uci commit

exit 0
